package com.cbp7.platform.notification.entity;

public enum NotificationType {
    REGISTRATION_SUCCESS,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    CERTIFICATE_READY,
    CERTIFICATE_ISSUED,
    ATTENDANCE_QR_GENERATED,
    VOLUNTEER_INVITATION,
    VOLUNTEER_ASSIGNED,
    VOLUNTEER_PERMISSIONS_UPDATED,
    VOLUNTEER_ACCESS_REVOKED,
    SESSION_REMINDER,
    GENERAL_NOTIFICATION
}
