export const GENDERS = ["MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY"]

export const COURSES = ["BTECH", "MTECH", "MBA"]

export const BRANCHES = [
  "CHEMICAL_ENGINEERING",
  "COMPUTER_SCIENCE_ENGINEERING",
  "CIVIL_ENGINEERING",
  "MECHANICAL_ENGINEERING",
  "ELECTRICAL_ENGINEERING",
  "ELECTRONICS_COMMUNICATION",
  "METALLURGICAL_ENGINEERING",
  "ARCHITECTURE",
  "ARTIFICIAL_INTELLIGENCE_DATA_SCIENCE",
  "MATERIALS_ENGINEERING",
  "MANAGEMENT_STUDIES",
  "OTHER",
]
