package com.cbp7.registration.enums;

public enum PublicRegistrationAuditEventType {
    REGISTRATION_CREATED,
    PAYMENT_ORDER_CREATED,
    PAYMENT_REDIRECTED,
    PAYMENT_CALLBACK_RECEIVED,
    PAYMENT_STATUS_CHECKED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REGISTRATION_COMPLETED,
    ACCOUNT_VERIFIED,
    PAYMENT_RETRY,
    DUPLICATE_REQUEST,
    PAYMENT_ERROR
}
