package com.cbp7.profile.entity;

public enum Branch {
    CHEMICAL_ENGINEERING,
    COMPUTER_SCIENCE_ENGINEERING,
    CIVIL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    ELECTRONICS_COMMUNICATION,
    METALLURGICAL_ENGINEERING,
    ARCHITECTURE,
    ARTIFICIAL_INTELLIGENCE_DATA_SCIENCE,
    MATERIALS_ENGINEERING,
    MANAGEMENT_STUDIES,
    OTHER
}
