spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    show-sql: true

logging:
  level:
    root: INFO

    # Your application logs
    org.springframework.context.support: DEBUG
    com.cbp7: INFO

    # Spring framework
    org.springframework: WARN

    # Hibernate
    org.hibernate: WARN

    # SQL logs
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

    # Spring Security
    org.springframework.security: WARN

    # OAuth debugging (keep only while debugging)
    org.springframework.security.oauth2: INFO

    # Database connection pool
    com.zaxxer.hikari: WARN