spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
